name: flutter_sodium
description: Flutter bindings for libsodium, a modern, easy-to-use crypto library.
version: 0.1.11
homepage: https://github.com/firstfloorsoftware/flutter_sodium

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^0.1.3
  convert: ^2.1.1
  meta: ^1.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.firstfloorsoftware.flutter_sodium
        pluginClass: FlutterSodiumPlugin
      ios:
        pluginClass: FlutterSodiumPlugin